#!/usr/bin/python
import numpy as np

def main():
    default = [3.9323,3.4309,2.1411,3.0592,1.4737,1.5042,2.9552,2.8689,1.0752,3.3626,2.3982, 3.5116]
    percent_imp = []
    try:
	ipc,num = np.loadtxt('grepIPC.csv',delimiter=',',unpack=True, dtype='str')
	
	i = 0
	for eachnum in num:
	    percent_imp.append(((float(num[i])/default[i])-1)*100)
	    i+=1
	
	average_imp = np.average(percent_imp)
	saveLine = str(average_imp)+'\n' 
	print str(average_imp)+'\n' 
	saveFile = open('average.xlsx','a')
	saveFile.write(saveLine)
	saveFile.close()
	    


    except Exception, e:
	print str(e)
	
    open('grepIPC.csv', 'w').close()
    percent_imp[:] = []

main()
